name: Publish Nuget Package

on:
  release:
    types: [released,prereleased]
    branches: [ main ]

jobs:
  publish-with-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: restore dependencies
      run: dotnet restore
    - name: build
      run: dotnet build --no-restore -c Release ./src/Cuture.AspNetCore.ResponseAutoWrapper/Cuture.AspNetCore.ResponseAutoWrapper.csproj
    - name: pack
      run: dotnet pack -c Release -o ./output --include-symbols
    - name: push package
      shell: pwsh
      working-directory: ./output
      run: Get-ChildItem -File -Filter '*.nupkg' | ForEach-Object { dotnet nuget push $_ -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json --no-service-endpoint --skip-duplicate; dotnet nuget push $_ -k ${{secrets.NUGET_GITHUB_KEY}} -s https://nuget.pkg.github.com/StratosBlue/index.json --no-service-endpoint --skip-duplicate; }
