name: Publish Nuget Package

on:
  release:
    types: [released,prereleased]
    branches: [ main ]

jobs:
  publish-with-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core 5 SDK
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET Core 3 SDK
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 3.1.x
    - name: restore dependencies
      run: dotnet restore
    - name: build
      run: dotnet build --no-restore -c Release
    - name: pack
      run: dotnet pack -c Release -o ./output --include-symbols
    - name: push package
      shell: pwsh
      working-directory: ./output
      run: Get-ChildItem -File -Filter '*.nupkg' | ForEach-Object { dotnet nuget push $_ -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json --no-service-endpoint --skip-duplicate; dotnet nuget push $_ -k ${{secrets.NUGET_GITHUB_KEY}} -s https://nuget.pkg.github.com/StratosBlue/index.json --no-service-endpoint --skip-duplicate; }
